apiVersion: v1
kind: ConfigMap
metadata:
  name: commoncrawl-config
  namespace: commoncrawl
data:
  COMMONCRAWL_VERSION: "CC-MAIN-2024-30"
  COMMONCRAWL_BASE_URL: "https://data.commoncrawl.org"
  CLUSTER_IDX_FILENAME: "/app/input/cluster.idx"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  BATCHER_BATCH_SIZE: "50"
  WORKER_METRICS_PORT: "9001"
  MIN_TEXT_LENGTH: "500"
  MAX_TEXT_LENGTH: "1000000"
  TOKENIZER_NAME: "bert-base-uncased"
  BUCKET_NAME: "extracteddata"

